CP LESSONS.....

1-> if you declare vector<pair<int,int> >v(N)-> then you must use v[i].push_back(make_pair(x,y))...
only v.push_back wouln't work..

2-> IN problems involving bits, think bit-wise i.e think about solving for one bit and then moving forward....motiv. 658 Div 2 C....
3-> TO FIND IF ONE ARRAY/STRING IS CYCLIC PERMUTATION OR NOT OF THE OTHER, CHECK IF AFTER CONCATENATING ARRAY 1 WITH ITSELF, U CAN FIND THE OTHER ARRAY/STRING IN IT AS A SUBSTRING...
4-> IF gcd(a,b)=x & lcm(a,b)=y:
	a= c*x,b= d*x -> c*x*d*x= a*b = x*y -> c.d= (y/x); so find all pair of divisors of
	(y/x) and multiply it with x to get a,b...

5-> BEWARE, declaring an array of size 1e6 inside main can give TLE but declaring it outside main will work... and this is for ARRAY ONLY, i.e. 4
    a vector of that size will work fine even inside main()..